### ISSUE TITLE
Need some basic documentation

### ISSUE THREAD

**Issue by pageauc** [fuzzycode/DawnDriver#1]
I have previously used the original dawn robot setup at DawnRobotics@bitbucket.org.  I can clone this repo per the following command
    git clone https://DawnRobotics@bitbucket.org/DawnRobotics/raspberry_pi_camera_bot
I don't believe this repo is being maintained
I found your github repo and would like to give it a try on my original Dawn Robot to do some testing with motion tracking, face detection and more sensors using a new RPI 3 using some previous code I had developed.  Would like to do more dev with better maintained and documented code infrastructure.  Not sure how your repo is implemented but can guess as some based on the original Dawn repo documentation.  I would like a bit of basic implementation instructions for your implementation.  Any help would be greatly appreciated.  Also I would be willing to write a wiki for your implementation similar to the original Dawn Robotics repo once I have figured things out..
Thanks Claude ...

**Comment by fuzzycode** [comment]
Hi,

I am sorry to disappoint you but my implementation is not very well maintained either. I have had my robot in boxes for the last 6 months so I have not looked or used the code for quite some time now.

If you are able to use the code, I am happy for you and any contribution or collaboration is highly welcome but I won't have time to work actively on the code in any foreseeable future my self :-(.

I think most of what I managed to do was to move files around and get a "better" structure of the code so my repo should still very much resemble the original driver.

I am sorry that I can not be of any more assistance to you.

Thanks
Björn

**Comment by fuzzycode** [comment]
I was not intending to control the robot over a http interface so I removed that part of the code. Worth keeping in mind if you do use the code. 

I also started the task of making it easier to install and use but I never got that far =(.

**Comment by pageauc** [comment]
Thanks

I know what you mean.  Life gets in the way.  I will work with the
bitbucket repo, clone to github and modify structure and code base to suit
what I want.  I do not like hard coded directory structures so will maybe
create a master config file for global configurations settings.  Hope your
robot won't get too lonely sitting in a box like in a Pixar Toy Story Movie.

Regards
Claude ..

On Sun, Apr 24, 2016 at 1:34 PM, Björn Larsson notifications@github.com
wrote:

> Hi,
> 
> I am sorry to disappoint you but my implementation is not very well
> maintained either. I have had my robot in boxes for the last 6 months so I
> have not looked or used the code for quite some time now.
> 
> If you are able to use the code, I am happy for you and any contribution
> or collaboration is highly welcome but I won't have time to work actively
> on the code in any foreseeable future my self :-(.
> 
> I think most of what I managed to do was to move files around and get a
> "better" structure of the code so my repo should still very much resemble
> the original driver.
> 
> I am sorry that I can not be of any more assistance to you.
> 
> Thanks
> Björn
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/fuzzycode/DawnDriver/issues/1#issuecomment-214004458

## 

See my YouTube Channel at http://www.youtube.com/user/pageaucp
